
package br.com.adenilson.mercado.view;

import br.com.adenilson.mercado.core.entity.PdvEntity;
import br.com.adenilson.mercado.core.entity.UserEntity;

/**
 *
 * @author Adenilson Konzelmann Alves <https://github.com/Adenilson365>
 */
public class TelaPdvOpenClose extends javax.swing.JFrame {

    /**
     * Creates new form PdvOpenClose
     */
    public TelaPdvOpenClose() {
        initComponents();
    }
    
    public TelaPdvOpenClose(UserEntity user,PdvEntity pdv){
        initComponents();
        System.out.println(pdv.getCash());
        jtValorGaveta.setText(String.format("%.2f",pdv.getCash()));
        jtValorGaveta.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtValorGaveta = new javax.swing.JTextField();
        jBConfirmarAbertura = new javax.swing.JButton();
        jBCancelarAbertura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Valor da Gaveta:");

        jtValorGaveta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtValorGaveta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtValorGaveta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtValorGavetaActionPerformed(evt);
            }
        });

        jBConfirmarAbertura.setText("Confirmar");
        jBConfirmarAbertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmarAberturaActionPerformed(evt);
            }
        });

        jBCancelarAbertura.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBConfirmarAbertura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBCancelarAbertura))
                    .addComponent(jtValorGaveta, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtValorGaveta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBConfirmarAbertura)
                    .addComponent(jBCancelarAbertura))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtValorGavetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtValorGavetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtValorGavetaActionPerformed

    private void jBConfirmarAberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmarAberturaActionPerformed
        // TODO add your handling code here:
        dispose();
        TelaPrincipalPDV tp = new TelaPrincipalPDV();
        tp.setVisible(true);
    }//GEN-LAST:event_jBConfirmarAberturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPdvOpenClose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPdvOpenClose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPdvOpenClose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPdvOpenClose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPdvOpenClose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelarAbertura;
    private javax.swing.JButton jBConfirmarAbertura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jtValorGaveta;
    // End of variables declaration//GEN-END:variables
}
